#!/bin/bash
set -e

SETUP_DIR="/app/setup"
CONFIG_DIR="${SETUP_DIR}/config"
BURP="https://git.ziirish.me/ziirish/burp.git"
BURP_VERSION="2.0.28"
BURPUI="https://burpui.ziirish.me/builds/burp-ui.dev.tar.gz"

# Install burp
git clone $BURP
cd burp
git checkout tags/$BURP_VERSION
./configure
make -j4
make install

# configure supervisord log rotation
cat > /etc/logrotate.d/supervisord <<EOF
/var/log/supervisor/*.log {
  weekly
  missingok
  rotate 52
  compress
  delaycompress
  notifempty
  copytruncate
}
EOF

# configure supervisord to start crond
cat > /etc/supervisor/conf.d/cron.conf <<EOF
[program:cron]
priority=20
directory=/tmp
command=/usr/sbin/cron -f
user=root
autostart=false
autorestart=true
stdout_logfile=/var/log/supervisor/%(program_name)s.log
stderr_logfile=/var/log/supervisor/%(program_name)s.log
EOF

cp ${CONFIG_DIR}/burp/* /etc/burp/

cat >>/etc/crontab<<EOF
54 1,3,5,7,9,11,13,15,17,19,21,23 * * * root burp -c /etc/burp/demo3.conf -a t &>/dev/null
29 0,2,4,6,8,10,12,14,16,18,20,22 * * * root burp -c /etc/burp/demo4.conf -a t &>/dev/null
EOF

# cleanup
rm -rf /var/lib/apt/lists/*
